sudo: required
services:
  - docker

before_install:
  - docker build -t nkavuri/springauth-ui -f ./ui/Dockerfile.dev ./ui
  - docker build -t nkavuri/springauth-api -f ./api/Dockerfile.dev ./api

script:
  - docker run -e CI=true nkavuri/springauth-ui npm test -- --coverage
  #- docker run -e CI=true nkavuri/springauth-api mvn test

after_success:
  - docker build -t nkavuri/springauth-ui ./ui
  - docker build -t nkavuri/springauth-nginx ./nginx
  - docker build -t nkavuri/springauth-api ./api
  
  # # Log in to the docker CLI
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # # Take those images and push them to docker hub
  - docker push nkavuri/springauth-ui
  - docker push nkavuri/springauth-nginx
  - docker push nkavuri/springauth-api

  
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "multi-docker2"
#   env: "Multidocker2-env"
#   bucket_name: "elasticbeanstalk-us-east-2-235502769638"
#   bucket_path: "docker-multi"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
