apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  #type: ClusterIP
  type: NodePort
  selector:
    component: ui
  ports:
    - port: 3000
      nodePort: 30036
      targetPort: 3000